version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: cbc_db
      POSTGRES_USER: cbc_user
      POSTGRES_PASSWORD: cbc_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  bcb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bcb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/cbc_db
      SPRING_DATASOURCE_USERNAME: cbc_user
      SPRING_DATASOURCE_PASSWORD: cbc_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  pgdata:

networks:
  backend:
