spring:
  application:
    name: bcb

  datasource:
    url: jdbc:postgresql://localhost:5432/cbc_db
    username: cbc_user
    password: cbc_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: 1
      password: password

server:
  port: 8080